### PR TITLE
feature works, now for GUI elements and such

### PR DESCRIPTION
**Pull request by gillett-hernandez**
addressed #31

### CODE REVIEW

**Review by EstevanBR — CHANGES_REQUESTED** [review]
Please save and load the held piece in tetris.dat

**Comment by gillett-hernandez** [comment]
can i refactor the loadGridFromFile and saveGridToFile methods to be somewhere else, like main.cpp? i feel like those methods are doing too much to be contained within GridController, for instance loading score and level data and soon to be loading and saving held pieces

i bring this up because loadGrid and saveGrid would have to somehow access a variable contained within the main function and that seems wrong

**Comment by EstevanBR** [comment]
> access a variable contained within the main function and that seems wrong

What variable? @gillett-hernandez

**Comment by gillett-hernandez** [comment]
The variable containing the held piece.

**Comment by EstevanBR** [comment]
@gillett-hernandez I'm fine with whatever you decide.

Maybe the variable should not exist in main at all, and it should be a public variable on the GridController itself? considering the grid controller is what is controlling the pieces and where they are in the grid.

**Pull request merged**
